### ISSUE TITLE
Indication of active filters

### ISSUE THREAD

**Issue by staubesv** [entwinemedia/annotations#385]
Currently, there is no way for the user to see whether one or more filters are active except to open the Filter dropdown menu.
This can be irritating.

In the following example, there are tracks. No track is available, however, because of all tracks being filtered:

![screen shot 2013-11-13 at 2 26 06 pm](https://f.cloud.github.com/assets/1590263/1531550/5bf5af70-4c67-11e3-8ae5-73ec5b9512ad.png)

The Filter drop down menu reveals the situation:

![screen shot 2013-11-13 at 2 26 32 pm](https://f.cloud.github.com/assets/1590263/1531552/6a0adb30-4c67-11e3-8b9f-fc94c3e3155f.png)

There should be some kind of indication whether one or more filters are active.

**Comment by Buttyx** [comment]
The filters are now replaced by the tracks / annotations selector in the latest version. Therefore I close it as wont fix.
