### ISSUE TITLE
Performance of startup in case of large number of annotations

### ISSUE THREAD

**Issue by staubesv** [entwinemedia/annotations#393]
For video clips that come with a large number of annotations, the application startup becomes terribly slow. The reason that for each single annotation, the front-end sends a HTTP GET request to the backend to retrieve the comments for that annotation.

A possible solution would be the introduction of an additional HTTP GET request (or may just an additional parameter for the existing one) that loads all annotations including all their comments at once.

**Comment by Buttyx** [comment]
The tool performance have been largely improve with the work done in the branch ANNOT-79, 83, 90, 97 and 101. The merge from the last to master should be done at the beginning of february.
