### ISSUE TITLE
Optimize performance of the tool

### ISSUE THREAD

**Issue by staubesv** [entwinemedia/annotations#394]
In #392 buttyx concluded:

A possible solution would be to reduce the number of DOM element to draw. It means try to remove all the useless element from the templates. 
Another related point directly related to the previous one is the frequency of the redraw. For the timeline this is difficult to reduce the number of total redraw as this is directly related to the timeline library. But for the list we could certainly reduce (even for a small amount) the number of small redraw. It means avoid full redraw if a simple DOM modification is possible.

**Comment by Buttyx** [comment]
The tool performance have been largely improve with the work done in the branch ANNOT-79, 83, 90, 97 and 101. The merge from the last to master should be done at the beginning of february.
