### ISSUE TITLE
Annotations visibility no indicated after startup and page reload

### ISSUE THREAD

**Issue by staubesv** [entwinemedia/annotations#398]
In both View->"Annotations visibility" and Timeline->"Other annotations", the currently active mode of annotations visibility ("My annotations only", "Other public annotations..." or "All public annotations") is not indicated.

Reproduction:
1. Open Annotation Tool
2. Look at  View->"Annotations visibility" or Timeline->"Other annotations

**Comment by Buttyx** [comment]
The annotations visibility selection is now also visible at startup.

**Comment by msohrmann** [comment]
What are the reasons to show either my annotations OR all public annotations ? I can well imagine the situation where I have my own private annotations that I would like to compare to available public annotations. This is currently not possible.
Suggestion: Make it possible to select "my annotations" and "all public annotations" or "selected public annotations" concomitantly.
This would imply to rename "my annotations only" to "my annotations".

**Comment by lauener** [comment]
I support the idea of Marc.
