### ISSUE TITLE
Default annotations visibility should be "My annotations only"

### ISSUE THREAD

**Issue by staubesv** [entwinemedia/annotations#399]
When the Annotation Tool is started, the default annotations visibility should be "My annotations only". This way, we can make sure that the tool is not stressed to much when loading a video with a lot of public tracks of other users.

Reproduction:
1. Open https://annotations.cast-test.switch.ch/clips/1aqe81mr0/annotate.html
2. You can now see public track of other users

**Comment by Buttyx** [comment]
The default annotations visibility is now set to my annotations but can be changed in the configuration through the function `getDefaultTracks`.
