### ISSUE TITLE
Layout problem when switching into edit mode in the annotation list

### ISSUE THREAD

**Issue by staubesv** [entwinemedia/annotations#400]
When double-clicking an collapsed annotation in the annotation list view, the annotation is expanded into the edit mode. Sometimes it happens that the annotation in question is then not visible in the list because the list is scrolled in a way that this annotation is not in the visible range of the list anymore.

Reproduction:
1. Open https://annotations.cast-test.switch.ch/clips/1aqe81mr0/annotate.html
2. Play 5 minutes with double-clicking annotations

**Comment by Buttyx** [comment]
If I have well understood the problem, it should be fixed through the commit [0bfd4d274f521b4860ee189fa4aef92eeb92297f](https://github.com/entwinemedia/annotations/commit/0bfd4d274f521b4860ee189fa4aef92eeb92297f).
