### ISSUE TITLE
Items visibility menu does not disappear after selection of item visibility

### ISSUE THREAD

**Issue by staubesv** [entwinemedia/annotations#401]
Reproduction:
1. Open "Annotation List View"->"Items visibility"
2. Click on either "Collapse All" or "Expand All"

Problem:
The Items Visibility menu should disappear after left-clicking a menu item.

**Comment by Buttyx** [comment]
Fix through commit [0bfd4d274f521b4860ee189fa4aef92eeb92297f](https://github.com/entwinemedia/annotations/commit/0bfd4d274f521b4860ee189fa4aef92eeb92297f).
