### ISSUE TITLE
Do we need more direct access to the trash can in the Annotation List View?

### ISSUE THREAD

**Issue by staubesv** [entwinemedia/annotations#402]
Currently, the trash can in the Annotation List View is only showed when an Annotation List View Entry in in "Edit-mode". This means that to delete an Annotation, the following steps are necessary:

a)
1. Double-click annotation to enter edit mode
2. Left-click trash can

b)
1. Left-click annotation->expand to expand annotation
2. Left-click "edit" to enter edit mode
3. Left-click trash can

The motivation of not showing the trash can icon in the collapsed representation of the annotation is to reduce the number of elements in the DOM to improve performance.

Is there a need to change the ways annotations can be deleted?

**Comment by Buttyx** [comment]
The annotations can be deleted by typing on the "delete" key. It gives the possibility to delete quickly an annotation.
