### ISSUE TITLE
Tool did not respond after changing Item visibility in the Annotation List View

### ISSUE THREAD

**Issue by staubesv** [entwinemedia/annotations#403]
Dominicq reported a problem he encountered when testing the current version of the annotation tool. When he changed the Items visibility, the browser reported that a script would no respond anymore.

I could unfortunately not reproduce this problem, so we need to gather more information about the browser and operating system used by Dominicq so way can try to reproduce his problem.

**Comment by Buttyx** [comment]
We definitely require more information about that. Could Dominicq reproduce it easily?

**Comment by Buttyx** [comment]
I am closing it since it seems that nobody is able to reproduce. Please reopen it with extended information if you are able to reproduce it.
