### ISSUE TITLE
Double-clicking annotation in Annotation List should not result in text selection

### ISSUE THREAD

**Issue by staubesv** [entwinemedia/annotations#404]
To edit an collapsed annotation, the annotation can be double-clicked in the Annotation List.

Currenlty, this results in the annotation being expanded into the edit mode (which is correct) and additionally "text selection" (see screenshot) which is not correct.

Note that this problem does not occur when the text of the collapsed annotation is double-clicked.

**Comment by staubesv** [comment]
![select](https://cloud.githubusercontent.com/assets/1590263/5837624/0e81952c-a181-11e4-8590-c6b0a0f87083.png)

**Comment by Buttyx** [comment]
As the double-click usage brings different strange behaviour of the target element, for example this text selection, it has been for now disabled.
