### ISSUE TITLE
Information about creator and creation date/time of annotations is not available anymore

### ISSUE THREAD

**Issue by staubesv** [entwinemedia/annotations#406]
When deciding to omit the "i" icon that was present for each collapsed annotation in the annotation list berfore, a requirement was that the information provided by the "i" icon must be available elsewhere.

Suggestions:
- Add this information (creator, creation date & time) to the expanded representation of each annotation
- The information is not needed in the edit mode of the annotation since only the creator can edit the annotation and to view the creation data/time, the creator can use the expanded representation
- Also add this information to the mouse-over showing the annotation text/label. This way, annotations do not have to be expanded to get the information

**Comment by msohrmann** [comment]
Agree with Sven. This information should be somewhere ...

**Comment by staubesv** [comment]
Do we also need the information about on which track the annotation is located? This information was available in the old version.
