### ISSUE TITLE
Access control: Creation of annotations of other users track

### ISSUE THREAD

**Issue by staubesv** [entwinemedia/annotations#412]
Reproduction:
1. Open SWITCHcast annotate! on cast-test.switch.ch on a video where multiple different users have created annotations (e.g. https://annotations.cast-test.switch.ch/clips/1aqe81mr0/annotate.html)
2. Show the other users public tracks 

Problem:
I could create annotations on the public default track of another user

**Comment by Buttyx** [comment]
This is related to #412. Please use this ticket if you have more information.

**Comment by Buttyx** [comment]
To reproduce it, choose to display the tracks from the other users but not yours. Then when you create a new annotation this one will be place on the track of another user.  It should not be possible.
