### ISSUE TITLE
ScaleValues cannot be deleted anymore

### ISSUE THREAD

**Issue by staubesv** [entwinemedia/annotations#418]
Reproduction:
1. Go to http://entwinemedia.github.io/annotations/#
2. Create a new ScaleValue
3. Try to delete the ScaleValue just created

Problem:
The ScaleValue cannot be deleted. The UI says "Warning! You are not authorized to deleted this scale value"

BTW: There is a typo in the warning message ("deleted" instead of "delete")

**Comment by staubesv** [comment]
This problem seems to be related to #411

**Comment by Buttyx** [comment]
The issue has been fixed and the updated version is available online on the following page:
http://entwinemedia.github.io/annotations/07-07-2015/
